# Generated by Django 4.0.1 on 2022-01-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='media.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='media.page'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='media.content'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='media.content'),
        ),
    ]
