# Generated by Django 4.0.1 on 2022-01-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_audio_content_alter_content_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='media.content'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='media.content'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='media.content'),
        ),
    ]
