# Generated by Django 4.0.1 on 2022-01-27 03:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_audio_content_alter_text_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['creation']},
        ),
        migrations.AddField(
            model_name='page',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='media.content'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='media.content'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='media.content'),
        ),
    ]
